### ISSUE TITLE
Peerfeedback

### ISSUE THREAD

**Issue by timmit147** [Mitzyyy/QuoteMe#2]
Ik zal de bestanden in mapjes doen zoals images,js,css

Ik denk dat je dit nodig hebt om het te laten zie hoe jij het wil.
ul > li {
    color: #292f3b;
    flex: 1 0 50%;
}
https://github.com/Mitzyyy/web-app-from-scratch-2122/blob/c0c12cd196ee80b7c72906f4965df7e4f186fc34/Eindopdracht/style.css#L26-L28

Ik zie niet veel fouten

**Comment by Mitzyyy** [comment]
Thanks! Ik heb het aangepast!
