### ISSUE TITLE
Feedback :)

### ISSUE THREAD

**Issue by farrahton** [Mitzyyy/QuoteMe#3]
**HTML**
- Voor meer overzicht de <ul> in een <main> zetten.

**CSS**

- Zorg voor meer consistentie in spaties.
Vb. 
body{
}

of

body { 
}
- Zelfde geldt voor waar je tabs gebruikt etc.
- Regel 36 en 37: je gebruikt vw voor width maar dan weer pixel voor height. Maak hier een keuze in welke van de units/eenheden je gebruikt.

**JS**
- Mooi duidelijke notities 
- Je zou nog modules kunnen toepassen en mapjes in het algemeen voor bestanden voor kortere code en overzichtelijkheid
- Regel 35 staat opeens een //3 functions notitie.

**Comment by Mitzyyy** [comment]
Thanks! Ik heb het aangepast!

**Comment by Mitzyyy** [comment]
Thanks! Ik heb het aangepast!
