### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Joepkl** [Mitzyyy/QuoteMe#4]
Duidelijke comments bij JS waardoor de code goed leesbaar is. Verder zou ik in je CSS een grid toevoegen zodat je de content makkelijk kan plaatsen zoals je in de wireflow hebt. Ook zou ik een form met input search toevoegen in de HTML voor je zoekbalk.

**Comment by Mitzyyy** [comment]
Thanks! Gedaan!

**Comment by Mitzyyy** [comment]
Thanks! Gedaan!
