### ISSUE TITLE
Aanroepen functie

### ISSUE THREAD

**Issue by EmileKost** [Mitzyyy/QuoteMe#5]
Volgens mij is het een bad practice om een functie aan te roepen voordat je hem declareert, dit heet hoisting dacht ik. Ik zou dit eventueel even aanpassen. Kwam hier laatst ook pas achte
<img width="239" alt="Schermafbeelding 2022-03-03 om 21 40 37" src="https://user-images.githubusercontent.com/70690100/156649393-8cbb0064-1b0a-4836-8e51-85ef5f637e2c.png">
r

**Comment by Mitzyyy** [comment]
Thanks!
